### ISSUE TITLE
SimpleHats causes crash when scrolling through the curios menu

### ISSUE THREAD

**Issue by KarratKake** [fonnymunkey/SimpleHats#29]
When SimpleHats is installed, using the scrollbar on the curios menu to scroll will instantly cause a crash. Crash log attached

[crash-2023-06-21_14.04.44-client.txt](https://github.com/fonnymunkey/SimpleHats/files/11828661/crash-2023-06-21_14.04.44-client.txt)

**Comment by fonnymunkey** [comment]
Nothing in that crash log nor the relevant code would suggest the crash has anything to do with SimpleHats.

I also loaded up an instance with a bunch of random Curios-related mods added to get the scrollbar in the Curios menu with SimpleHats, and scrolling didn't crash, it worked fine.

This suggests to me that if you're crashing, its likely caused by some other mod and/or interactions between multiple mods, so I recommend trying to remove as many mods as you can before the crash stops happening to figure out which mods those are.

**Comment by fonnymunkey** [comment]
Closing as no response.
