### ISSUE TITLE
RGB Doesn't work 1.19.2 (Fabric)

### ISSUE THREAD

**Issue by LyroHP** [fonnymunkey/SimpleHats#34]
All hats freeze on one color and won't do RGB

**Comment by spicylimetaco** [comment]
my rgb hat is bugging too, was tinkering with resource packs and it simply stopped showing up on my head but still changes colors as an item. other hats work fine tho. even set simple hats resource pack to top priority and no change

**Comment by fonnymunkey** [comment]
SimpleHats does nothing special for the RGB effect, it is a normal Vanilla animated texture.

I believe there is a setting in the options to turn off animated textures, which either of you may have accidentally enabled.

Otherwise, I know there are multiple "performance" mods that forcibly disable animated textures, which you may have added and/or enabled.

The only other thing would be if you overrode the texture files when trying to edit them but left out the proper files for it to animate, such as the .mcmeta.

**Comment by fonnymunkey** [comment]
Closing as no response.
