### ISSUE TITLE
Crash on World Load

### ISSUE THREAD

**Issue by Airisii** [fonnymunkey/SimpleHats#41]
Crash with latest update causes my game to crash when loading into a world. It seems the curios fix is causing some kind of issue with my game. If needed I can try and narrow down the cause but I have about 700 mods and it could take a while to find the cause. Also version 0.2.1 works just fine, its only this new update that this is happening.

Crash: 
[crash-2023-09-03_19.09.20-client.txt](https://github.com/fonnymunkey/SimpleHats/files/12508133/crash-2023-09-03_19.09.20-client.txt)

**Comment by fonnymunkey** [comment]
You're using Curios 5.2.0-beta.3, which is outdated now as Curios 5.2.0 release was uploaded 2 days ago.
Curios reworked a bunch of internal methods which broke SimpleHats 0.2.1, which is why 0.2.2 was released.
Either update Curios to 5.2.0 release, or downgrade SimpleHats to 0.2.1.
The only change from 0.2.1 to 0.2.2 is compat with the Curios update, there's no reason to update if you can't update Curios.

**Comment by Airisii** [comment]
Oh, I'm so sorry I wasn't aware my curios was out of date I thought I check I must of over looked it, I do apologize. Thank you for pointing that out for me tho. Have a nice day! :)
