### ISSUE TITLE
[Feature Request] Client config for hat particles

### ISSUE THREAD

**Issue by milkev** [fonnymunkey/SimpleHats#42]
**Description**
A client side config to reduce and/or fully disable the particles that some hats produce.

**Why**
Mostly for first person model mod compatability. I want my hats to still be viewable in inventory/shader shadows like they are without turning on force disable hat render in first person. I know there is particle settings in graphics but that encompasses all particles in the game and I just want to remove the hat particles but keep everything else.

![image](https://github.com/fonnymunkey/SimpleHats/assets/22010128/2bcc6dee-f29f-4287-88cd-50cd9068901f)

**Comment by fonnymunkey** [comment]
You can modify particle settings for each hat on clientside in config/simplehats.json.
If you're having issues with too many particles or particles covering the screen using first person renders, there are options to reduce the frequency, or change the trailing type to TRAILING_FEET instead of TRAILING_HEAD.

**Comment by milkev** [comment]
i didnt realize this was already an option!

i will note that this config is not visible in game using mod menu, while the other config files in config/simplyhats are

**Comment by fonnymunkey** [comment]
The other config options are viewable in-game as they are part of the general config for more generic options that an end-user would interact with while playing, the simplehats.json is not as it is unique to entries for hats that show up in-game and can change the hats registered in-game if you renamed/add/remove entries from it which can cause world/server issues if modified haphazardly and is meant for modpack devs instead of end-users (The sub-section of hat entries labelled particle-settings is the only part that shouldn't cause any world/server issues as it is fully client side.)
