### ISSUE TITLE
Fabric 1.19.2. Can't get hats to render

### ISSUE THREAD

**Issue by KapsiF** [fonnymunkey/SimpleHats#43]
I can see them when I hold them in my hand but I can't get them to work. I can also see the particles but the mesh and textures are just messed up and I can't see any of the hats and if I do see them they are messed up textures.
Trinkets, Cloth Config, Continuity and Mod Menu installed.

**Comment by KapsiF** [comment]
![image](https://github.com/fonnymunkey/SimpleHats/assets/73310940/4974ff70-e3ec-4079-9824-d86fa4ddf9ca)
In my head are the headphones w messed up textures and in my hand is correctly rendered floating hearts

**Comment by KapsiF** [comment]
![image](https://github.com/fonnymunkey/SimpleHats/assets/73310940/5efc0af5-dcb1-4a58-9e1b-0acfa52de85d)
Here are the hearts in my head

**Comment by KapsiF** [comment]
![image](https://github.com/fonnymunkey/SimpleHats/assets/73310940/56a0a230-72fc-46a8-93c6-da4e6222b392)
So I imagine the animation is having problems?

**Comment by fonnymunkey** [comment]
I believe this is an incompatibility either with Continuity itself, or one of its settings, since anytime this issue is reported its always with using Continuity. I've tested with Continuity before and didn't have these issues so either its a version issue or a config issue.

You can try temporarily removing Continuity to see if it fixes it, and if so maybe change some settings.
Alternatively you may be having this issue: https://github.com/PepperCode1/Continuity/issues/107 and need to install Indium with Sodium for Continuity to function properly.

**Comment by KapsiF** [comment]
Yea I'll try it without Continuity since I do have Indium installed

**Comment by fonnymunkey** [comment]
Closing as assumed resolved.
