### ISSUE TITLE
Not able to equip any hats

### ISSUE THREAD

**Issue by Medicane** [fonnymunkey/SimpleHats#51]
I'm not able to equip any hats. The slots to equip them doesn't exist. I play on fabric (over modrinth) and have all the dependencies installed and on the newest version. I play on 1.20.4 btw

**Comment by fonnymunkey** [comment]
I'm not able to reproduce this, what version of Trinkets are you using?
Do any trinket slots show up when you mouse over the armor slots, or none at all?
You may have a mod conflicting with the inventory.

**Comment by Medicane** [comment]
Im using 1.20.4-0.2.3 but ive also tried it with 0.2.2 for 1.20.4. And no nothing shows up. In my inventory the charachter etc is also alligned a bit differently. About the mods: I've tried it only with the 2 mods that have to be there + the fabric api wich is mandatory

**Comment by fonnymunkey** [comment]
Can you upload your latest.log file from the logs folder?

**Comment by Medicane** [comment]
[2024-02-23-4.log.gz](https://github.com/fonnymunkey/SimpleHats/files/14391122/2024-02-23-4.log.gz)

**Comment by fonnymunkey** [comment]
You're using [Trinkets Polymer](https://modrinth.com/mod/trinkets-polymer) not [Trinkets](https://modrinth.com/mod/trinkets)
My mod is made for Trinkets.
Polymer uses a command to open a GUI to equip trinkets, it does not use the inventory slot overlay, which is why you can not equip hats that way.
It seems to be meant for being used on a server for vanilla clients to join (Which does not make sense to me with how Trinkets works.)

**Comment by Medicane** [comment]
ohhhhhhh. ok. Thanks. Sry
