### ISSUE TITLE
[Feature Request] Allow Same Hats To Stack

### ISSUE THREAD

**Issue by RyanSalad** [fonnymunkey/SimpleHats#54]
I love this mod so much, but I always run into issues with clutter from these hats. I've tried downloading mods that allow you to configure custom stack sizes but they always have some incompatibility with xyz other mod and make me crash on startup. 

I also want to make note that I've been building modpacks on either 1.19.2 or 1.20.1, so if you have to focus in on a version or two for time or something, then I'd say those are the current definitive versions.
Thanks in advance

**Comment by fonnymunkey** [comment]
I responded to a similar question on the discord and as such forgot to respond here, woops.

I have no plans to make hats stack-able, as they are equip-able items like armor which can have issues arise from being made stack-able.

Besides potential issues from hats being stack-able, you can break down hats by crafting them with shears, which will give you hat scraps which can be crafted into new bags to get new hats. The intention is if you have multiple of the same hat, you will recycle the extras instead of hanging on to them.

**Comment by RyanSalad** [comment]
Okay I understand your reasoning, but I should mention that it is extremely tedious to break down and recycle a lot of hats. I don't yet have a suggestion for a better way to do that, but I want that to be known as a reason why I desire hat stacking
