### ISSUE TITLE
Hat grab bag text box won't go away

### ISSUE THREAD

**Issue by Mushrumie** [fonnymunkey/SimpleHats#74]
On the right side of my screen in the middle, there's a text box that says "Uncommon Hat Bag 100%" (or something like that) but I don't know how to get rid of it. I don't have a hat bag in my inventory anymore, I opened the ones I have. I've pressed every button on my keyboard. Please help :(( 

![Screenshot_20240718-131205](https://github.com/user-attachments/assets/0e1e242f-16b6-4c04-932d-095574d08522)

**Comment by fonnymunkey** [comment]
My mod does nothing related to rendering text/popup like that, that is some other mod you have that likely desynced and thinks you are still holding the hat bag, if you are playing a modpack you should report that issue to the modpack developer otherwise try to find whatever mod is responsible for adding extra item popups.
